import latest from '../../data/latest.json';
import history from '../../data/history.json';
import { buildEvidence } from './evidence.mjs';
export const snapshot = latest;
export const auto = latest.auto || {};
export const manual = latest.manual || {};
export const meta = latest.meta || {};
export const generatedUtc = latest.generatedUtc;
export const hist = Array.isArray(history) ? history : [];
export const evidence = buildEvidence(latest, hist);
